Version: "v0.1"
# path (prefix) of where *raw* data live (BCLs)
# this is organized per RUN
datadir: "/eva/datums/fresh"

# path (prefix) of where *finished* (e.g., bams/vcfs, reports) live
# this is organized per STUDY/CASE
# (with hooks back to the datadir; note this includes the samplesheet!
donedir: "/eva/datums/cooked"

# path (prefix) of where *live/active data live*
# organized per study/case
workdir: "/eva/staging/"

# a lookup table, converting an instrument identifier (lhs) into its common name (rhs)
instrumentlut: 
    A01324: NovaSeq001
    M50235: MiSeq003
    M50337: MiSeq001
    M50342: MiSeq002


# Needed for parsing BCLs
Samplesheet: "SampleSheet.csv"

# Sequencing libraries need to be tracked.
SamplesheetLibraryColumn: "I7_Index_ID" # a fairly sensible default; if the same sample is prepped twice, 
# you'll get better performance if you use a different adapter. Or you can track the library explicitly

# we generally assume that you're running snakemake from within the BCL directory
# you can flag it in, however
Bcldir: "." 

# If not set on the command line, this comes from the "Experiment name" field in the sample sheet
Experiment: ""
# automatically writes data to the parent directory of the BCL directory
Outdir: ".."
# (of the form Outdir/Experiment)

# Needed for parsing FASTQs
Reads: "Fastqs/*R1*fastq*"
Samplename: ""
# UD conforms to UDI and UDP
Offtarget_index_prefix: "UD"

# performance enhancement; write temporary files to local disk (ideally, NVME drives)
# the current systems mount an entire drive to /tmp
tmpdirprefix: "/tmp" # this is a prefix. for example: (mktemp -d --tmpdir={tmpdir} XXXXXXglimpse2)

# note that considerable effort would be needed to add "X" to this list...
chroms: "1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22" # bash quality of life improvement. {1..22} equivalent, noting that {} is snakemake-syntax too!


refs:
    Reference: "/eva/codebase/resources/hg38/GRCh38_full_analysis_set_plus_decoy_hla.fa"
    Hg19: "/eva/codebase/resources/hg19/chrAll.standardChroms.fa"

bcl2fastqParams:
    binary: "/eva/codebase/bin/bcl2fastq"
    params: "--minimum-trimmed-read-length 0 --ignore-missing-bcls "
    threads: 256

bwamemParams:
    threads: 50
    binary: "bwa"

samtoolsParams:
    binary: "samtools"
    sortMem: "50G"
    samtoolsThreads: 4
    mem_mb_sort: 200000 # sort SORT alone; 50Gb * 4 threads

sambambaParams:
    binary: "/eva/codebase/bin/sambamba"
    threads: 32
    memmb: 20000 # really, it's the size of the file. hopefully this is good enough
   
gatkParams:
    binary: "/eva/codebase/bin/gatk"
    bqsrargs: "--QUIET --lenient" 
    javaoptions: "-Xmx10G"
    liftoverChain: "/eva/codebase/resources/hg38ToHg19.over.chain"
    liftoverOptions: "--VERBOSITY ERROR --COMPRESSION_LEVEL 9 --RECOVER_SWAPPED_REF_ALT true --QUIET true --CREATE_INDEX true --WRITE_ORIGINAL_ALLELES true --WRITE_ORIGINAL_POSITION true --WARN_ON_MISSING_CONTIG true"


demixtifyParams:
    binary: "/eva/codebase/bin/demix"
    summarizer: "Rscript /eva/codebase/bin/mfPretty.R" # pretties up the output...
    panel: "/eva/codebase/resources/GSA-24v3-0_A2.hg38.gnomadannos.autos.sites2include.justafs.bcf" # suitable for mixture detection.
    threads: 4
    

fastqcParams:
    binary: "fastqc"

bcftoolsParams:
    binary: "bcftools"
    #512 max depth; min mapqual:20 and min base quality of 10 ; ignore indels ; recalculate BAQs; add the following annotations
    mpileup_options: "-d 512 -q 20 -Q 10 -I -E -a 'FORMAT/DP,FORMAT/AD,FORMAT/SP'"
    panel: "/eva/codebase/resources/hgdp1kgp_autos.filtered.SNV_INDEL.phased.shapeit5.unrelateds.nopp.sites.tsv.gz"
    threads: 4

deepvarParams:
    dvthreads: 120
    binary: "/opt/deepvariant/bin/run_deepvariant"
    version: 'docker://google/deepvariant:"1.4.0-gpu"' # users may need to update the config file here.
    
atlasParams:
    binary: "/eva/codebase/bin/atlas"
    threads: 10 # we use chromosome-level parallelization. 10 is (in practice) a good balance (22 would maximize performance)
    mergeargs: "updateQuality silent" #arguments to splitMerge
    bqsrargs: "estimateBQSRPosition estimateBQSRPositionReverse estimateBQSRContext maxPos=1000 window=1000000 minEpsQuality=0.001 minEpsFactors=0.001 storeInMemory verbose"
    bqsrmask: "/eva/codebase/resources/atlas.excludesites.bed"
    summarizer: "Rscript /eva/codebase/bin/plot_pmd.R"
  
glimpse2Params:
    ligate_binary: "/eva/codebase/bin/GLIMPSE2_ligate_static"
    phase_binary: "/eva/codebase/bin/GLIMPSE2_phase_static"
    reference_database_prefix: "/eva/codebase/resources/split/2.0"
    threads: 40


samstatsParams:
    binary: "python3 /eva/codebase/bin/samStats.py" # uses the panel; computes stats at the sites in the panel; includes coverage/breadth/template lengths, read lengths
    panel: "/eva/codebase/resources/gsa_24v3-0_A2.GRCh38.rand10k.bed"
    summarizer: "Rscript /eva/codebase/bin/samstats2cov.R" # provides a more succinct summary of the samstats file.