Version: "v.21"
# Changelog:
# 09/2024
# Added X chromosome support (glimpse and bcftools)
# includes estimating X ploidy, then genotyping wrt to that ploidy
# Added chromosome-level parallel support for genotyping (bcftools)
# and added "matchiness" support; still in development mode
# 10/2024
# set the glimpse min mapping quality to 20 (default is 10)
# 23andme files are now made using a custom script. (previously used bcftools query)
# 12/24
# changed bcf223andme; default bayes factor now 1.7, gp>0.99
# also changed bcftools call from Aim to Am (missing sites are now missing from the VCF)
# 3/25
# Refactor. No tools changed, but the directory structure is made more sane.


# Needed for parsing BCLs
# defaults to $BCLDIR/SampleSheet.csv
Samplesheet: "SampleSheet.csv"
# Note that Samplesheet and SampleSheet are permitted variable names. (SampleSheet takes precedence)


# Sequencing libraries need to be tracked.
SamplesheetLibraryColumn: "I7_Index_ID" # a fairly sensible default; if the same sample is prepped twice, 
# you'll get better performance if you use a different adapter. Or you can track the library explicitly

# we generally assume that you're running snakemake from within the BCL directory
# you can flag it in, however
Bcldir: "" 


# If not set on the command line, this comes from the "Experiment name" field in the sample sheet
Experiment: ""


# Needed for parsing FASTQs
Reads: "Fastqs/*R1*fastq*"

# UD conforms to UDI and UDP
# This can be modified, but the prefix (UD) cannot be used by any *real* sample
# ie, it can only be used for unindexed results
# (which are data that demultiplex for some index not thought to have been sequenced)
Offtarget_index_prefix: "UD"

# Used to convert bam -> vcf
Samplename: ""
# Bam suffix:
# non-empty suffix; can either be 'la.md.bqsr'
# (left-align, mark duplicates, base quality score recalibration; aka, bqsr)
# OR
# la.md
# (Not using BQSR doesn't make a lot of sense though)
Suffix: "la.md.bqsr"

# performance enhancement; write temporary files to local disk (ideally, NVME drives)
# the current systems mount an entire drive to /tmp
tmpdirprefix: "/tmp" # this is a prefix. for example: (mktemp -d --tmpdir={tmpdir} XXXXXXglimpse2)

# note that X calling routines are entirely separate.
chroms: "1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22" # bash quality of life improvement. {1..22} equivalent, noting that {} is snakemake-syntax too!

# rules for the below:
# All relative paths (at least on /)
# are relative to the parent directory of this file
# 
# executables/binaries
# same relative path rule as above AND
# if it's a bareword (atlas, fastqc)
# it's assumed to be callable from the environment (ie, that it's in your PATH
# absolute paths are respected (kept as is)
# when used w/ GenomixHelper.py
# Rscript/python3 are prepended to .R and .py files/paths (this goes for both "binary" and "summarizer" tokens)

# the reference genome(s)
refs:
    Reference: "resources/hg38/GRCh38_full_analysis_set_plus_decoy_hla.fa"
    Hg19: "resources/hg19/chrAll.standardChroms.fa"

bcl2fastqParams:
    binary: "bin/bcl2fastq"
    params: "--minimum-trimmed-read-length 0 --ignore-missing-bcls --create-fastq-for-index-reads  --fastq-compression-level 9"
    threads: 256
    xtra: ""

bclconvertParams: 
    binary: "bin/bcl-convert"
    params: "--force --sample-name-column-enabled true --create-fastq-for-index-reads true --fastq-gzip-compression-level 9"
    threads: 256
    xtra: ""

bwamemParams:
    threads: 50
    binary: "bwa"

samtoolsParams:
    binary: "samtools"
    sortMem: "50G"
    samtoolsThreads: 4
    mem_mb_sort: 200000 # sort SORT alone; 50Gb * 4 threads

sambambaParams:
    binary: "bin/sambamba"
    threads: 32
    memmb: 20000 # really, it's the size of the file. hopefully this is good enough
   
gatkParams:
    binary: "bin/gatk"
    bqsrargs: "--QUIET --lenient" 
    javaoptions: "-Xmx10G"
    liftoverChain: "resources/hg38ToHg19.over.chain"
    liftoverOptions: "--VERBOSITY ERROR --COMPRESSION_LEVEL 9 --RECOVER_SWAPPED_REF_ALT true --QUIET true --CREATE_INDEX true --WRITE_ORIGINAL_ALLELES false --WRITE_ORIGINAL_POSITION true --WARN_ON_MISSING_CONTIG true"
    bqsrmask: "resources/atlas.excludesites.bed.gz"

demixtifyParams:
    binary: "bin/demix"
    summarizer: "bin/mfPretty.R" # pretties up the output...
    panel: "resources/GSA-24v3-0_A2.hg38.gnomadannos.autos.sites2include.justafs.bcf" # suitable for mixture detection. less so for deconv.
    threads: 4
  
# for identifying matchiness  
# this work is also shelved; using a stringent Bayes factor threshold tends to make (nearly all) matchiness problems go away.
matchinessParams:
    ibis_binary: "bin/ibis"
    ibis_script: "bin/add-map-plink.pl"
    ibis_threads: 62
    plink_binary: "bin/plink"
    filterer: "bin/multiFilterVcf.py"
    panel: "resources/plinkgsa/merged_ref_overlappedGSA" # pre-built plink file of GSA sites in the imputation panel
    gsavcf: "resource/GSA-24v3-0_A2.hg38.gnomadannos.autos.sites2include.justafs.vcf.gz" # Global screening array sites, autosomes, annotations from gnomad
    gmap: "resources/ibis.sexaveraged.hg38.gmap"

fastqcParams:
    binary: "fastqc"

bcftoolsParams:
    binary: "bcftools"
    #512 max depth; min mapqual:20 and min base quality of 10 ; ignore indels ; recalculate BAQs; add the following annotations
    mpileup_options: "-d 512 -q 20 -Q 10 -I -E -a 'FORMAT/DP,FORMAT/AD,FORMAT/SP'"
    panel: "resources/bcftools_call/hgdp1kgp_autos.filtered.SNV_INDEL.phased.shapeit5.unrelateds.nopp.sites.chr" # must end in chr\d.tsv.gz (for \d in 1-22)
    xpanel: "resources/chrX/bcftools/1kGP_high_coverage_Illumina.chrX.filtered.SNV_INDEL_SV_phased_panel.v2.nonpar_subsamp_nosingletons_justsnps.tsv.gz"
    threads: 4
    callthreads: 10 # supports per chromosome genotyping;

deepvarParams:
    dvthreads: 120
    binary: "/opt/deepvariant/bin/run_deepvariant" # binary is wrt to the image (sif). i.e., this should be an absolute path (and need not exist on the system you run this on)
    image: "bin/deepvariant_latest.sif"

# Atlas is so incredibly resource intensive, this work is shelved for now. perhaps
# future versions of Atlas will be more palatable.  
atlasParams:
    binary: "bin/atlas"
    threads: 10 # we use chromosome-level parallelization. 10 is (in practice) a good balance (22 would maximize performance)
    mergeargs: "updateQuality silent" #arguments to splitMerge
    bqsrargs: "estimateBQSRPosition estimateBQSRPositionReverse estimateBQSRContext maxPos=1000 window=1000000 minEpsQuality=0.001 minEpsFactors=0.001 storeInMemory verbose"
    bqsrmask: "resources/atlas.excludesites.bed"
    summarizer: "bin/plot_pmd.R"
   
glimpse2Params:
    ligate_binary: "bin/GLIMPSE2_ligate_static"
    phase_binary: "bin/GLIMPSE2_phase_static"
    phase_options: "--mapq 20"
    reference_database_prefix: "resources/split/2.0"
    reference_database_prefix_chrX: "resources/chrX/glimpse2/reference_panel/split/2.0"
    threads: 40

samstatsParams:
    binary: "bin/samStats.py" # uses the panel; computes stats at the sites in the panel; includes coverage/breadth/template lengths, read lengths
    panel: "resources/gsa_24v3-0_A2.GRCh38.rand10k.bed"
    summarizer: "bin/samstats2cov.R" # provides a more succinct summary of the samstats file.

# Note that the X/autosomes regions are parallel (same coordinates, different chromosomes)
# we use the relative number reads in these regions to directly estimate the X ploidy (estimated using relative read depth)
# also note that the X/A loci are singular (1 region), while the Y regions (should we use those) are a BED file (Poznik et al 2013)
sexchromosomeParams:
    xregion: "resources/X_nonpar.txt"
    aregion: "resources/7_matching_X.txt"
    yloci: "resources/Poznik.YChromCallable.hg38.bed"
    xestimator: "bin/estimateXPloidy.R"
    samflags: "3968" # excludes reads if any bit set: see https://broadinstitute.github.io/picard/explain-flags.html

bcf223andmeParams:
    binary: "bin/bcf223andme.py"
    snpfile: "resources/snppanel_autos_x.vcf.gz" # only used when making the "SNP" files.
    annotationsfile: "resources/hgdp1kgp_autos_sites.filtered.SNV_INDEL.phased.shapeit5.unrelateds.nopp.gnomad3_1_2anno.hg19.vcf.gz" # population allele frequencies (hg19) come 
    annotations: "AF_nfe,AF_fin,AF_afr,AF_ami,AF_eas,AF_sas,AF_amr,AF_asj,AF_mid" # add allele frequency information the the following populations.
    bcffilt: "" # only used when making the "SNP" files. Additional arguments to bcftools can be placed here.
    glimpse2: "-x -b 1.7 -p 0.99" # (bcf223andme.py) filters for glimpse2; Include the X; Bayes Factor > 1.7; Genotype Posterior > 0.99
    bcftools: "-x -q 20" # (bcf223andme.py)  filters for bcftools; Include the X; Genotype quality >= 20
    
    